### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by chrissearle** [javaBin/javazone-ios-app#8]
Spec ?

**Comment by lokling** [comment]
From what I´ve gathered and can remember, anyone please correct if wrong: 
- Backend is devnull, doc on who https://github.com/javaBin/devnull . 

Rumoured wishes for the feedeback functionality: 
- Timed window where feedback can be given? (do we want that?)
- Freetext field feedback for general comments.
- Please rate the session reminder

PKOM- maybe you can add any wishes?

**Comment by lokling** [comment]
@raphw  I think you mentioned a wish for feedback functionality last jz workshop?

**Comment by raphw** [comment]
Would be nice if one could give simple feedback (1-3 similar to the paper) and a comment in the app.

**Comment by chrissearle** [comment]
OK - devnull has the following feedback structure - which will dictate the input needed:

```
{
  "overall" : 1-5,
  "relevance" : 1-5,
  "content" : 1-5,
  "quality" : 1-5,
  "comments": "String"
}
```

It also takes a Voter-ID header - so I hope that means it handles double posts.

Don't know if it has an open/close time for a session.

We can either add a local table to remember input - in which case this can be part of the standard view since we can display previous input - or not - in which case its more of a popup type input.

For feedback to be simpler (as in @raphw comment) the structure in devnull would have to be simpler (or we have to agree only to give the "overall" input with values of 1-3)

Notifiications - will think about this. I used to have statistics on how many people used local notifications from the earliest app (your next session is in room X in 5 mins) - but I don't have them any more. I never got any direct feedback that they were appreciated - but I did get a couple of reports that they were irritating (despite being something the user could control). But that was years ago. Do we have any stats from the newer apps on notification enable/disable use?

**Comment by chrissearle** [comment]
This will be the next thing to be worked on.

We need to know exactly what feedback we want to collect in the apps this year (the full devnull spec or a subset?)

We also need to know some bits beyond the API:

* When should a session feedback open?
* When (if ever) should a session feedback close?
* Is there a test instance of devnull?
* If not - can we use the main one?
* What sessions does devnull know about?

Might be @ingarabr who can answer some of these (around test etc)

**Comment by chrissearle** [comment]
Feedback from @ingarabr - devnull feedback has been shut down.

@raphw what is the status for 2020 ?

**Comment by chrissearle** [comment]
Closing - reopen if we actually want this
